alias egrep='egrep --color=auto'
alias fgrep='fregp --color=auto'
alias grep='grep --color=auto'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -ahlF'
alias ls='ls --color=auto'
alias nano='nano -lmq'
alias rcon='docker exec -i minecraft-server rcon-cli'
alias reboot='sudo reboot now'
alias update='sudo apt update -y'
alias updatelist='apt list --upgradeable'
alias upgrade='sudo apt update -y && sudo apt upgrade -y'
